server:
  port: 8080

sharding:
  env: shardingOnly   #配置环境使用哪种配置文件shardingOnly,shardingAndMasterSlave
  #Sharding配置文件路径
  sharding_config_file: yamlShardingDatabaseAndTable.yaml
  #Sharding_master_slave配置文件路径
  sharding_ms_config_file: yamlShardingAndMasterSlave.yaml
#sharding jdbc config
#sharding:
#  jdbc:
#    datasource:
#      names: ds-0,ds-1
#      ds-0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://135.251.208.160:3306/ds_0?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#        username: root
#        password: root
#      ds-1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://192.168.23.163:3306/ds_1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#        username: root
#        password: root@1qa2ws
#    config:
#      sharding:
#        default-database-strategy:
#          inline.sharding-column: user_id
#          inline.algorithm-expression: ds-$->{user_id % 2}
#        tables:
#          t_order:
#            table-strategy:
#              inline:
#                sharding-column: order_id
#                algorithm-expression: t_order_$->{order_id % 2}
#            actual-data-nodes: ds-$->{0..1}.t_order_$->{0..1}
#            keyGeneratorColumnName: order_id
#          t_order_item:
#            actual-data-nodes: ds-$->{0..1}.t_order_item_$->{0..1}
#            keyGeneratorColumnName: order_item_id
spring:
  datasource:
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

      ######Druid监控配置######
      #配置WebStatFilter
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #配置StatViewServlet
      stat-view-servlet:
        login-username: admin
        login-password: 8080
      #spring监听配置
      aop-patterns: 'com.lyu.study.test.service.*'

      ######多数据源配置######
      one:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://135.251.208.160:3306/ds_0?characterEncoding=utf8&useSSL=true&serverTimezone=PRC&nullNamePatternMatchesAll=true
        username: root
        password: root
      two:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.23.163:3306/ds_1?characterEncoding=utf8&useSSL=true&serverTimezone=PRC&nullNamePatternMatchesAll=true
        username: root
        password: root@1qa2ws

      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://135.251.208.160:3306/ds_0?characterEncoding=utf8&useSSL=true&serverTimezone=PRC&nullNamePatternMatchesAll=true
        username: root
        password: root
      master1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.23.163:3306/ds_1?characterEncoding=utf8&useSSL=true&serverTimezone=PRC&nullNamePatternMatchesAll=true
        username: root
        password: root@1qa2ws

mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: com.qianq.shardingmybatis.entity
